// <auto-generated />
namespace Hotel_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_orderby : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_orderby));
        
        string IMigrationMetadata.Id
        {
            get { return "202001310943275_remove_orderby"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
