// <auto-generated />
namespace Hotel_Final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class at_last : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(at_last));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141918438_at_last"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
